name: Deploy to Salesforce
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli
      - name: Authenticate with Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > authfile
          sf org login sfdx-url --sfdx-url-file authfile --alias MyDevOrg
      - name: Deploy to Salesforce
        run: sf project deploy start --target-org MyDevOrg --source-dir force-app